on:
  push:
      branches:
        - main

name: 🚀 Deploy to Production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build Project
      env:
        CI: false
        GENERATE_SOURCEMAP: false
        REACT_APP_MAIN_SYSTEM_URL: ${{ secrets.PRODUCTION_REACT_APP_MAIN_SYSTEM_URL }}
        REACT_APP_API_HOST: ${{ secrets.PRODUCTION_REACT_APP_API_HOST }}
        REACT_APP_LOGO_URL: ${{ secrets.PRODUCTION_REACT_APP_LOGO_URL }}
      run: yarn build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.PRODUCTION_FTP_HOST }}
        username: ${{ secrets.PRODUCTION_FTP_USERNAME }}
        password: ${{ secrets.PRODUCTION_FTP_PASSWORD }}
        local-dir: build/
        server-dir: /
